### ISSUE TITLE
name-clash with a pre-existing dotfile manager?

### ISSUE THREAD

**Issue by moesasji** [hlmtre/homemaker#19]
Great to see your efforts in writing a dotfile manager in rust. However I actually stumbled on your code because I was actually looking for https://github.com/FooSoft/homemaker. More complete description of how that one works here: https://foosoft.net/projects/homemaker/ 

As this dotfile-manager has been around for a number of years. It might be worth pointing to that one somewhere in your readme, even if just as an alert?

btw) the "original" homemaker actually has some nice ideas; not clear to me whether it is still maintained. In that sense it could be a nice source of inspiration as well.

**Comment by hlmtre** [comment]
AWwww shucks you're absolutely right. I will include a little blurb explaining the clobbering. Thanks!
