### ISSUE TITLE
Cannot load gif url

### ISSUE THREAD

**Issue by ngirard** [hlmtre/homemaker#4]
I couldn't visit the url mentioned in the README: https://gfycat.com/skinnywarmheartedafricanpiedkingfisher

Cheers

**Comment by hlmtre** [comment]
Hm, loads for me:
https://i.imgur.com/9AwllfB.png

Can you get to other gfycat videos?

**Comment by ngirard** [comment]
I can access it now... go figure.
Closing.

**Comment by hlmtre** [comment]
Well thank you for taking a look, and taking the time to report an issue as you saw it. What brought you to `hm`?

**Comment by ngirard** [comment]
IIRC I stumbled upon it because it was tagged `#tmux` on lib.rs, as I was looking for session managers for Tmux written in Rust -- believe it or not, there are 3 of them !

I may be interested in using Homemaker to manage my dotfiles though, but TBH it would help if there was a bit more documentation and examples, especially how it compares to existing tools and what makes it different !

**Comment by hlmtre** [comment]
Absolutely, thank you for the suggestions! I got it to this working, happy state, and sort of halted. I have some time this weekend actually set aside to work on this, though, so I'll compare it to existing tools and add some more documentation.

**Comment by ngirard** [comment]
Great ;-)

**Comment by hlmtre** [comment]
https://docs.rs/hm/
